server:
  port: ${SERVER_PORT:8081}
  servlet:
    context-path: /api/v1

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:15432/api-user
    username: api-user
    password: api-user
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:/liquibase/changelog-master.xml
  sql:
    init:
      platform: postgres
logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
  pattern:
    console: "[%thread][%highlight(%-5level)][%cyan(%d{yyyy-MM-dd HH:mm:ss})][%yellow(%X{requestId})][%magenta(%logger{40})] - %msg%n"